### ISSUE TITLE
Support for server side rendering?

### ISSUE THREAD

**Issue by digz6666** [concludio/react-mathlive#23]
It says document is not defined when used with server side rendering.
```
node_modules\mathlive\dist\mathlive.js:11955
     const gScriptUrl = (_b = (_a = document.currentScript) === null || _a === void 0 ? void 0 : _a.src) !== null && _b !== void 0 ? _b : getFileUrl();
[1]                        ^
[1]
[1] ReferenceError: document is not defined
[1]     at node_modules\mathlive\dist\mathlive.js:11955:24
[1]     at node_modules\mathlive\dist\mathlive.js:2:68

```

**Comment by ramon-adan** [comment]
Any update regarding this?

**Comment by arnog** [comment]
Note that this is fixed in the current version of MathLive (0.72.1).

**Comment by Mopiel** [comment]
We are using 0.77.0 and this is the output 
![image](https://github.com/concludio/react-mathlive/assets/52651964/f666ed4a-74b5-4270-9243-fde1cfcaff82)

**Comment by arnog** [comment]
I would recommend trying the current version, with is 0.95.5.
